version: '0.0.1'

services:
  rabbitmq_service:
    image: rabbitmq:3-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    networks:
        - main_network

  parser_service:
    build:
      context: apartments_parser/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq_service
    networks:
      - main_network

  tg_bot_service:
    build:
      context: telegram-bot-service/
      dockerfile: build/Dockerfile
    logging:
      options:

    depends_on:
      - rabbitmq_service
    networks:
      - main_network

networks:
  main_network:
    driver: bridge